In [1]:
import mysql.connector

In [24]:
db = mysql.connector.connect(
    host="localhost",
    user="root",
    passwd="uche",
    database=""
    )

In [4]:
mycursor = db.cursor()

In [5]:
#mycursor.execute("CREATE TABLE Person (name VARCHAR(20), age smallint UNSIGNED, personID int PRIMARY KEY AUTO_INCREMENT)")

In [6]:
#mycursor.execute("INSERT INTO Person (name, age) VALUES (%s,%s)", ("Joe", 19))
#db.commit()
#mycursor.execute("SELECT * FROM Person")

In [7]:
#for x in mycursor:
    #print(x)

In [8]:
#mycursor.execute("CREATE TABLE sit (name varchar(20) NOT NULL, created datetime NOT NULL, gender ENUM('M', 'F', '0') NOT NULL, id int PRIMARY KEY NOT NULL AUTO_INCREMENT)")

In [9]:
#mycursor.execute("INSERT INTO sit (name, created, gender) VALUES(%s,%s,%s)", ("TIM", datetime.now(), "M"))
#db.commit()

#mycursor.execute("SELECT * FROM Test WHERE gender * 'M' ORDER BY id DESC")
mycursor.execute("SHOW DATABASES")
for x in mycursor:
    print(x)

In [19]:
mycursor = db.cursor()

mycursor.execute("SHOW TABLES")

for x in mycursor:
  print(x)

('actor',)
('actor_info',)
('address',)
('category',)
('city',)
('country',)
('customer',)
('customer_list',)
('faac_2020',)
('film',)
('film_actor',)
('film_category',)
('film_list',)
('film_text',)
('inventory',)
('language',)
('nicer_but_slower_film_list',)
('payment',)
('rental',)
('sales_by_film_category',)
('sales_by_store',)
('staff',)
('staff_list',)
('store',)

In [23]:
mycursor = db.cursor()
mycursor.execute("SELECT * FROM faac_2020")
myresult = mycursor.fetchall()
for x in myresult:
    print(x)

(1, 'ABIA STATE', 2856640370, 2646920172, 2363484966, 2688879058, 2490155558, 2250421954, 2734858404, 2810930839, 2773895905, 2596618258)
(2, 'ADAMAWA STATE', 3558570430, 3299781555, 2951196566, 3342944259, 3107031846, 2806790553, 3422409363, 3521173689, 3469056745, 3245543006)
(3, 'AKWA IBOW STATE', 4787699108, 4480229192, 3975088679, 4519596452, 4184880669, 3771090719, 4587373302, 4717716605, 4642221805, 4341768102)
(4, 'ANAMBRA STSTE', 3664816610, 3379305620, 3034416217, 3445664112, 3197689890, 2894086980, 3506918152, 3652901346, 3619022330, 3405984445)
(5, 'BAUCHI STATE', 4039919496, 3738855319, 3353442557, 3804630021, 3537197522, 3188040146, 3878092965, 3983143760, 3943155666, 3704418262)
(6, 'BAYELSA STATE', 1633939426, 1550936159, 1374002332, 1539824664, 1462036983, 1295228924, 1568937191, 1600343397, 1601635186, 1494693258)
(7, 'BENUE STATE', 4223851998, 3896596114, 3463541420, 3945070871, 3811578838, 3432016945, 4159104745, 4276390960, 4250539470, 3958235984)
(8, 'BORNO STATE', 4758159137, 4397582151, 3938928589, 4471277526, 4164819788, 3740754843, 4545066619, 4668850626, 4604694090, 4311309574)
(9, 'CROSS-RIVER STATE', 3054200372, 2824287948, 2525596284, 2868068399, 2704875775, 2434720698, 2962334529, 3040418003, 3002500951, 2811179250)
(10, 'DELTA STATE', 4111298336, 3804384843, 3357915895, 3840198232, 3687491597, 3258598922, 3967940067, 4018714705, 3981350398, 3738568339)
(11, 'EBONYI STATE', 2268707806, 2101351354, 1863424036, 2175618814, 2032712657, 1836944957, 2214383863, 2295217926, 2250801402, 2122765904)
(12, 'EDO STATE', 3087218418, 2646920172, 2565263953, 2903682949, 2690190321, 2436244969, 2960451005, 3052677575, 3000302456, 2823032749)
(13, 'EKITI STATE', 2469231151, 2284185260, 2045554153, 2326392621, 2152765023, 1953709758, 2384508272, 2437212212, 2426876508, 2289194190)
(14, 'ENUGU STATE', 3132927063, 2909767031, 2572716780, 2979957766, 2717820165, 2464029771, 2989409511, 3053362878, 3025274736, 2850580443)
(15, 'GOMBE STATE', 2096872627, 1926192829, 1694915242, 1930676959, 1849982094, 1671423759, 2038133101, 2086125918, 2069551367, 1931310044)
(16, 'IMO STATE', 4203985540, 3894200504, 3491674708, 3977195226, 3669947625, 3349650055, 4039068240, 4145147303, 4083767503, 3820493930)
(17, 'JIGAWA STATE', 4429357481, 4093227775, 3656023335, 4146192890, 3864852524, 3483696939, 4228315347, 4350067930, 4294930965, 4027073677)
(18, 'KADUNA STATE', 5067253595, 4570622569, 4057896493, 4603899196, 4253841927, 3844670167, 4717186724, 4807872487, 4845013018, 4550897963)
(19, 'KANO STATE', 8023909741, 7398160643, 6623368114, 7577601612, 7004130256, 6360687525, 7697555252, 7962123286, 7879251053, 7397586478)
(20, 'KATSINA STATE', 5939814689, 5483658073, 4905098333, 5566684126, 5184157204, 4683673372, 5670713594, 5828589938, 5804459759, 5390876603)
(21, 'KEBBI STATE', 3691129045, 3426525330, 3059489247, 3471729870, 3235899135, 2901674212, 3527173741, 3631978673, 3592624923, 3351618498)
(22, 'KOGI STATE', 3427781624, 3145886161, 2773911812, 3198235471, 3327499090, 2984963717, 3629534074, 3726546047, 3704031740, 3437498750)
(23, 'KWARA STATE', 2721850299, 2529008029, 2254609914, 2562254883, 2374870281, 2142342140, 2616081618, 2672851775, 2640952789, 2474649328)
(24, 'LAGOS STATE', 8568091538, 8865922888, 8449184890, 9918421842, 8590886838, 8147078705, 10157844006, 10970711105, 10887249946, 10640825817)
(25, 'NASARAWA STATE', 2331538383, 2161846216, 1920955889, 2210215023, 2087559680, 1873459667, 2267231264, 2327954862, 2301802732, 2153123204)
(26, 'NIGER STATE', 4474574549, 4132468392, 3693351525, 4197594291, 3900178201, 3517925430, 4271266830, 4382755626, 4341975739, 4061846190)
(27, 'OGUN STATE', 3257818118, 3004365115, 2682992240, 3020786465, 2882731017, 2627161017, 3206284561, 3292280835, 3255827763, 3056079368)
(28, 'ONDO STATE', 3077195375, 2845021778, 2563141849, 2893085134, 2725161404, 2468910597, 2994371633, 3079630872, 3044656346, 2873295431)
(29, 'OSUN STATE', 4175016861, 3857932830, 3457313474, 3929495106, 3719943550, 3362632491, 4095063233, 4214370737, 4127164000, 3860383158)
(30, 'OYO STATE', 5485914128, 5098173262, 4573078736, 5260343489, 4872631911, 4426277140, 5303155641, 5537803788, 5464675850, 5282052160)
(31, 'PLATEAU STATE', 3286595425, 3021310943, 2713009231, 3056277467, 2846555612, 2562152988, 3105972115, 3193881879, 3165165786, 2959835429)
(32, 'RIVERS STATE', 4397687971, 3980220127, 3644523436, 4182629109, 3811428469, 3510358329, 4367258097, 4349327824, 4389778900, 4178591848)
(33, 'SOKOTO STATE', 4033661924, 3737306445, 3335680683, 3783174046, 3564335153, 3208055711, 3900967805, 3997946362, 3954714368, 3714498859)
(34, 'TARABA STATE', 2991411433, 2796251222, 2464528447, 2798742586, 2614908903, 2382382608, 2850972429, 2965713798, 2878281701, 2694245350)
(35, 'YOBE STATE', 3034000626, 2814349607, 2507655602, 2838688082, 2659072777, 2389623330, 2894216501, 2984962060, 2947863889, 2752081581)
(36, 'ZAMFARA STATE', 2788370911, 2582616915, 2312742310, 2626399703, 2439093233, 2194223196, 2678420521, 2740967594, 2727760217, 2545697933)
(37, 'FEDERAL CAPITAL TERRITORY (FCT)', 3495755856, 2361208479, 2037645815, 2300083133, 1915653536, 2226318197, 2821770606, 2365588575, 3282755520, 2455479052)